[package]
name = "etching"
version = "0.1.0"
edition = "2021"
authors = ["thinkgos <thinkgo@aliyun.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# local dependencies
entity = {path = "entity"}

actix-web = "4"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
thiserror = "1"
tracing = {version = "0.1", features = ["log"]}
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.3"
tracing-log = "0.1"
tracing-actix-web = "0.7"
secrecy = {version = "0.8", features = ["serde"]}
sea-orm = {version = "0", features = [ "sqlx-mysql", "runtime-tokio-rustls", "macros"]}
sea-query = "0"
config = "0.13"

bytes = "1"
prost = "0.11"
# Only necessary if using Protobuf well-known types:
prost-types = "0.11"

[build-dependencies]
prost-build = "0.11"