//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub mod prelude;

pub mod announce;
pub mod banner;
pub mod banner_kind;
pub mod dict;
pub mod dict_item;
pub mod guide;
pub mod perm;
pub mod question;
pub mod resource;
pub mod role;
pub mod sys_role_user;
pub mod sys_user;
