[package]
name = "entity"
version = "0.1.0"
edition = "2021"
authors = ["thinkgos <thinkgo@aliyun.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sea-orm = {version = "0"}
serde = { version = "1", features = ["derive"] }