//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "app_version")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub client_type: u8,
    pub is_force: i8,
    pub version: String,
    pub name: String,
    pub app_url: String,
    pub content: String,
    pub remark: String,
    pub hint: String,
    pub button_label: String,
    pub is_enabled: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
