//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "dict_item")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub dict_id: i64,
    pub key: String,
    pub name: String,
    pub value: String,
    pub sort: u32,
    pub remark: String,
    pub is_enabled: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
