//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "geo_map")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub pid: String,
    pub deep: String,
    pub name: String,
    pub ext_path: String,
    #[sea_orm(column_type = "custom(\"GEOMETRY\")")]
    pub geo: String,
    #[sea_orm(column_type = "custom(\"GEOMETRY\")")]
    pub polygon: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
