//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "invoice_pending")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub orders_id: i64,
    pub uid: i64,
    pub has_apply: i8,
    pub has_abandon: i8,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
