//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "pay_refund_record")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: u64,
    pub orders_id: u64,
    pub pay_orders_id: u64,
    pub trade_no: String,
    #[sea_orm(column_type = "Decimal(Some((16, 2)))")]
    pub refund_amount: Decimal,
    pub r#type: i32,
    pub status: i32,
    pub refund_reason: i32,
    pub refund_desc: String,
    pub refund_time: i64,
    pub interval: i64,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
