//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "perm")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub sub_id: i64,
    pub sub_type: u8,
    pub obj_id: i64,
    pub obj_type: u8,
    pub eft: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
