//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_sign")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uid: i64,
    pub signed_subject_uid: i64,
    pub signed_subject_bank_card_id: i64,
    pub signed_subject_card_no: String,
    pub signed_subject_company_name: String,
    #[sea_orm(column_type = "Decimal(Some((12, 6)))")]
    pub crowdsourcing_ratio: Decimal,
    #[sea_orm(column_type = "Decimal(Some((16, 4)))")]
    pub balance: Decimal,
    pub remark: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
