//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "withdraw")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub uid: i64,
    pub channel: i32,
    #[sea_orm(column_type = "Decimal(Some((16, 4)))")]
    pub amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((16, 4)))")]
    pub fee: Decimal,
    pub trade_no: String,
    pub receipt_account: String,
    pub is_virtual: i8,
    pub status: u8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub tryingd_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
